### ISSUE TITLE
Trouble extracting the Windows version of Alpha 6

### ISSUE THREAD

**Issue by aagricola** [vanevery/p5.serialcontrol#16] opened 2017-11-10 16:15 UTC
I have a student trying to use the p5.serialcontrol version 6 for windows and they are having trouble simply extracting the file. They can extract the version 5, but it only lists the ports but does not offer the option to open ports or enable. 

The inability to extract version 6 is strange and it may be my lack of experience with windows, but I'm wondering if this is an issue others have had and if there is a fix?

Here are screenshots of the issues: 

<img width="588" alt="alpha5error" src="https://user-images.githubusercontent.com/6782516/32667207-0fa4f26a-c608-11e7-8cbb-85356d05beb6.PNG">

<img width="439" alt="serialcontrolerror" src="https://user-images.githubusercontent.com/6782516/32667211-110b68b4-c608-11e7-8418-76b15464cb0f.PNG">

**Comment by vanevery** [comment] 2017-11-10 17:27
Hi @aagricola your student isn't alone.  We have had a similar report from another user and it seems we need to repackage the latest alpha build for Windows.

With regards to using Alpha 5, you can enable the full interface by hitting the "escape" key 1 or 2 times.  Alpha 5 has a memory leak which causes it's performance to drop over time (over the course of hours and days) but for development it should be fine.

**Comment by aagricola** [comment] 2017-11-10 17:44
Thank you @vanevery ! We will give Alpha 5 another try with that suggestion.

**Comment by vanevery** [comment] 2017-11-10 19:01
Great!  Please let me know if that works.  Will try to build a new Windows version next week.

**Comment by hx2A** [comment] 2017-11-13 14:54
@vanevery @aagricola , the Alpha 6 Windows archive is unzip-able on a Linux machine so the zip archive is valid. It isn't unzip-able from Windows.

I was able to get the files I needed onto my Windows machine by using Linux as an intermediary but got an unusual error when I tried to copy it from a thumb drive to Windows. Some of the subdirectories can't be copied because "the file name(s) would be too long for the destination folder." I skipped those directories (there are many). The skipped directories seem to be unimportant as the executable works just fine.

Perhaps the problem is the length of some of the directory names? Did you include files in v6 that aren't in v5? A parsimonious zip archive might be a good solution.

**Comment by vanevery** [comment] 2017-11-13 19:59
Thanks @hx2A  I can confirm the problem as well and we'll do a new windows build that hopefully alleviates it.  It may very well be the long file names that are causing the issue. 
 See: https://github.com/nodejs/node-v0.x-archive/issues/6960 and https://github.com/npm/npm/issues/3697

**Comment by montoyamoraga** [comment] 2022-07-26 03:55
since we have released new versions, we are closing this for now

**Closed as completed by montoyamoraga** 2022-07-26 03:55 UTC
Labels: bug
